---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create directory
  file: 
    path: .circleci/backend
    state: directory

- name: copying files
  become: true
  copy:
    src: artifact.tar.gz
    dest: .circleci/backend

- name: unzip artifact
  become: yes
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start